import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { analyzeIssue } from "../src/analyzer.js";
import { DEFAULT_CONFIG } from "../src/config.js";
import {
  buildSuggestedReply,
  COMMENT_MARKER,
  renderJson,
  renderMarkdown,
  renderTerminal,
} from "../src/renderer.js";
import type { IssueInput, ReproductionReport } from "../src/types.js";

function fixture(name: string): string {
  return readFileSync(new URL(`./fixtures/${name}`, import.meta.url), "utf8");
}

function analyzeFixture(name: string, title: string): ReproductionReport {
  const input: IssueInput = { title, body: fixture(name), source: { type: "markdown" } };
  return analyzeIssue(input, DEFAULT_CONFIG);
}

describe("renderMarkdown", () => {
  it("always contains the comment marker", () => {
    const report = analyzeFixture("incomplete-issue.md", "Login broken");
    const markdown = renderMarkdown(report);
    expect(markdown).toContain(COMMENT_MARKER);
    expect(markdown).toContain("## 🔎 Issue2Repro");
    expect(markdown).toContain("**Reproduction readiness: 25%**");
    expect(markdown).toContain("Status: **Insufficient**");
  });

  it("lists available and missing information", () => {
    const report = analyzeFixture("incomplete-issue.md", "Login broken");
    const markdown = renderMarkdown(report);
    expect(markdown).toContain("- ✅ Problem description");
    expect(markdown).toContain("- ✅ Operating system");
    expect(markdown).toContain("- ❌ Application version");
    expect(markdown).toContain("- [ ] Application version");
    expect(markdown).toContain("- [ ] Exact reproduction steps");
    expect(markdown).toContain("Generated by Issue2Repro.");
  });

  it("includes detected details for rich issues", () => {
    const report = analyzeFixture("good-issue.md", "Login fails");
    const markdown = renderMarkdown(report);
    expect(markdown).toContain("### Detected details");
    expect(markdown).toContain("OS: macOS 15");
    expect(markdown).toContain("Application version: 2.1.0");
  });

  it("includes the suggested maintainer reply only in report variant", () => {
    const report = analyzeFixture("incomplete-issue.md", "Login broken");
    expect(renderMarkdown(report, { variant: "comment" })).not.toContain(
      "### Suggested maintainer reply",
    );
    expect(renderMarkdown(report, { variant: "report" })).toContain(
      "### Suggested maintainer reply",
    );
  });
});

describe("renderJson", () => {
  it("produces machine-readable ReproductionReport JSON", () => {
    const report = analyzeFixture("good-issue.md", "Login fails");
    const parsed = JSON.parse(renderJson(report)) as ReproductionReport;
    expect(parsed.title).toBe("Login fails");
    expect(parsed.readinessScore).toBe(100);
    expect(parsed.readinessStatus).toBe("excellent");
    expect(parsed.reproduction.steps).toHaveLength(3);
    expect(parsed.environment.os).toBe("macOS");
    expect(Array.isArray(parsed.missingFields)).toBe(true);
  });
});

describe("renderTerminal", () => {
  it("shows the box, progress bar and status", () => {
    const output = renderTerminal(analyzeFixture("incomplete-issue.md", "Login broken"), {
      color: false,
    });
    expect(output).toContain("Issue2Repro");
    expect(output).toContain("Login broken");
    expect(output).toContain("25%");
    expect(output).toContain("Status: Insufficient");
    expect(output).toContain("✗ Application version");
    expect(output).toContain("✗ Exact reproduction steps");
    expect(output).not.toContain("\u001b[");
  });

  it("renders steps for complete issues", () => {
    const output = renderTerminal(analyzeFixture("good-issue.md", "Login fails"), {
      color: false,
    });
    expect(output).toContain("1. Open the application");
    expect(output).toContain("100%");
  });

  it("uses ANSI colors when enabled", () => {
    const output = renderTerminal(analyzeFixture("good-issue.md", "Login fails"), {
      color: true,
    });
    expect(output).toContain("\u001b[");
  });
});

describe("buildSuggestedReply", () => {
  it("is deterministic for the same missing fields", () => {
    const missing = ["app_version", "reproduction_steps"];
    expect(buildSuggestedReply(missing)).toBe(buildSuggestedReply(missing));
  });

  it("asks for every missing field", () => {
    const reply = buildSuggestedReply(["app_version", "os_version", "expected_behavior"]);
    expect(reply).toContain("application version");
    expect(reply).toContain("operating system version");
    expect(reply).toContain("expected behaviour");
    expect(reply).toContain("Thanks for the report.");
  });

  it("reports readiness when nothing is missing", () => {
    expect(buildSuggestedReply([])).toContain("ready to reproduce");
  });
});
